# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {}
# META }

# MARKDOWN ********************

# # 🚀 **Getting Started — Fabric Spark Performance Workshop**
# 
# Welcome! This notebook is your launchpad for the day. Run through it once before Module 0 to
# confirm your environment is ready, seed the bronze Delta tables, and get oriented to the
# materials.
# 
# **Time required:** ~10–15 minutes (most of it is waiting for the seeding job to finish)
# 
# ---
# 
# ## What you'll do here
# 
# 1. ✅ Verify prerequisites (workspace, attached lakehouse, Fabric Environment)
# 2. 🧱 Trigger the `source_to_bronze` Spark Job Definition to build the bronze layer
# 3. 🔍 Validate the bronze tables landed correctly
# 4. 🗺️ Get oriented to the LEGO data model and the workshop modules


# MARKDOWN ********************

# ---
# 
# ## 🗺️ The LEGO Lakehouse — Data Model
# 
# Throughout the workshop we use a synthetic LEGO manufacturing & sales lakehouse generated by
# [LakeGen](../LakeGen/). The diagram below shows the full schema — fact tables (events,
# orders, transactions) at the center, dimensions (parts, colors, themes, sets) on the
# periphery.
# 
# ![Lego Manufacturing and Sales Schema](https://github.com/mwc360/fabric-spark-performance-workshop/blob/main/assets/lego_erd.png?raw=true)
# 
# > 💡 The biggest fact table is `manufacturing_event` (~8 M rows / ~350 MB). Most performance
# > exercises target it because it's the only table large enough to make Spark break a sweat at lab scale on a single node.


# MARKDOWN ********************

# ---
# 
# ## 1️⃣ Seed the Bronze Layer — Run `source_to_bronze`
# 
# The workshop's source data does not live in the lakehouse yet. The first thing you'll do is
# run a **Spark Job Definition** that:
# 
# 1. Generates LakeGen LEGO landing data (mixed JSON + Parquet) into `Files/landing/…`
# 2. Ingests every table through ArcFlow into bronze Delta tables under the `bronze` schema
# 
# ### 🎯 How to trigger it
# 
# 1. Go to the [source_to_bronze](https://app.powerbi.com/groups/$workspaceId/sparkjobdefinitions/$sparkJobDefinitionId?experience=fabric-developer) Spark Job Definition
# 1. Click **Run** (top header ribbon). _Note: only click **Run** once. It takes ~5 seconds to show up as active in the run history._
# 
# > 🔁 **Re-run anytime.** The job is incremental — run it multiple times to generate larger lab data. By default it will run for 30 minutes and then stop. By this time, most Delta tables will have ~ 150 commits.
# 
# > ⚠️ **Don't run the `source_to_bronze_optimized` job** yet. That variant is run later.
# 
# Move onto lab 1 once the Spark Job Definition run shows as **Succeeded**.


# MARKDOWN ********************

# ---
# 
# ## 2️⃣ Workshop Modules — Where to Go Next
# 
# There are four hands-on labs.
# Each lab is one or multiple notebooks in this workspace.
# 
# | Module | Notebook | What you'll learn |
# |--------|----------|--------------------|
# | **1 — Performance Diagnostics** | `01-lab-diagnostics.ipynb` | Reading the Spark UI, query plans, and Delta metadata to localize bottlenecks |
# | **2 — Configuration & Tuning** | `02-configuration-and-table-design.ipynb` | OPTIMIZE / compaction, deletion vectors, liquid clustering, data skipping stats |
# | **3 — Optimization Patterns** | `03-lab-optimization.ipynb` | Join strategies, caching, AQE, shuffle tuning |
# | **4 — Advanced Debugging** | `04-debugging.ipynb` | Triage 5 reproducible failure modes end-to-end |
# 
# ### Helper / shared notebooks
# 
# | Notebook | What it provides |
# |----------|------------------|
# | `_benchmark_utils.ipynb` | `benchmark_op(scenario, state, spark)` context manager and `get_table_metrics()` / `show_metrics()` helpers used across labs. Don't run it standalone — the lab notebooks `%run` it. |

